name: test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Installing NASM
        run: sudo apt update && sudo apt install nasm

      - name: Show test file
        run: |
          pwd
          ls -R
          sed -n '1,120p' tests/src/test.c

      - name: Run tests
        run: make test 