name: test

on:
  push:
    branches:
      - main
      - dev/types
  pull_request:
    branches:
      - main
      - dev/types

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run tests
        run: make test
  